version: 0.2
phases:
  install:
    commands:
      - echo "Installing..."
  build:
    commands:
      - echo "Zip for Lambda...".
      - zip -r build.zip user.js admin.js doctor.js appointment.js
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws --version
      - aws configure set region us-east-2
      - aws lambda update-function-code --function-name clinic-api-user --zip-file fileb://build.zip
      - aws lambda update-function-code --function-name clinic-api-admin --zip-file fileb://build.zip
      - aws lambda update-function-code --function-name clinic-api-doctor --zip-file fileb://build.zip
      - aws lambda update-function-code --function-name clinic-api-appointment --zip-file fileb://build.zip
      - echo "DONE...!!"